dim_flt 1
dim_act 2
dim_frm 1

findactor 0,"pol2"
findactor 1, "Detektiv3"
findframe 0,"pol2"

enemy_vidim 0

frm_seton 0,0
act_setstate -1,inactive
frm_seton 0,1

{ down
enemy_vidim 1
label 101
wait 25000
goto 101
}
enemy_usecar
enemy_vidim 1

enemy_look 1
enemy_wait
enemy_vidim 1

label 102
enemy_move 6,run
goto 102

event 201
commandblock 1
enemy_vidim 0
enemy_brainwash
enemy_forcescript 0
commandblock 0
return
