act_setstate -1, inactive
dim_flt 1
label DETECT
wait 250
detector_inrange 0, 20
if flt[0] ! 0, DETECT, -1
dim_act 5
findactor 0, "forVfor4"
findactor 1, "Enemy_gr4_1"
findactor 2, "Enemy_gr4_2"
findactor 3, "Enemy_gr4_3"
findactor 4, "Enemy_gr4_4"
dim_frm 1
findframe 0, "position_AUTO2"
actor_setplacement 0, 0
act_setstate 1, active
act_setstate 2, active
act_setstate 3, active
act_setstate 4, active