commandblock 1
dim_frm 2
dim_flt 1
dim_act 5
findactor 0, "polimFor3"
findactor 1, "pol6"
findactor 2, "pol5"
findactor 3, "Tommy"
findactor 4, "sirene3"
findframe 0, "stopka3"
commandblock 0

enemy_vidim 0
human_addweapon 1, 11, 8, 16
human_addweapon 2, 8, 6, 24
enemy_usecar 0, 0
act_setstate 1, inactive
wait 36000
//enemy_car_moveto 0, 0
enemy_car_escape 0, 3, 0
enemy_usecar
act_setstate 4, off
setevent 2, 1, -1
//enemy_action_fire 3, 10
enemy_vidim 1
enemy_podvadim_jak tretera
label 1
goto 1