dim_flt 1
dim_act 1
dim_frm 1
findframe 0
findactor 0,"Tommy"

setcompass 0

label 101
detector_waitforuse 02970001
vlvp 0
if flt[0]=1,-1,POLICIE_NEVIDI
rnd 0,3
  if flt[0]=0,-1,113
  human_talk 0,00950223
  label 113
  if flt[0]=1,-1,114
  human_talk 0,00950224
  label 114
  if flt[0]=2,-1,115
  human_talk 0,00950225
  label 115
goto 101

label POLICIE_NEVIDI
garage_show
change_mission "intermezzo03" , "" , -1
