dim_act 1
dim_flt 1
findactor 0,"Tommy"

label 101
detector_waitforuse 10970000
vlvp 0
if flt[0]=1,-1,POLICIE_NEVIDI
rnd 0,3
  if flt[0]=0,-1,113
  human_talk 0,00950223
  label 113
  if flt[0]=1,-1,114
  human_talk 0,00950224
  label 114
  if flt[0]=2,-1,115
  human_talk 0,00950225
  label 115
goto 101

label POLICIE_NEVIDI

change_mission "mise08-hotel", "load z mise08-mesto", -1 
//change_mission "mise08-hotel", "", -1 


