//vlajky

DIM_FRM 4
DIM_FLT 2

FINDFRAME 0, "vlajka1"
FINDFRAME 1, "vlajka2"
FINDFRAME 2, "vlajka3"
FINDFRAME 3, "vlajka4"

label 1
  rnd 0, 3  
  let flt[0] = flt[0] * 1000
  let flt[0] = flt[0] + 3000
  wait flt[0]
 rnd 1, 8
 IFFLTINRANGE 1, 0, 1, 2
 IFFLTINRANGE 1, 2, 3, 3
 IFFLTINRANGE 1, 4, 5, 4
 IFFLTINRANGE 1, 6, 7, 5

label 2
 FRM_SETON 0, 1
goto 1

label 3
 FRM_SETON 1, 1
goto 1

label 4
 FRM_SETON 2, 1
goto 1

label 5
 FRM_SETON 3, 1
goto 1