dim_flt 1
dim_act 7
findactor 0, "vagcisterna4"
findactor 1, "vagcisterna3"
findactor 2, ""
findactor 3, "naraz2"
findactor 4, "csii4"
findactor 5, "naraz1"
findactor 6, "csii2"

act_setstate 100, inactive

label 1
getactorsdist 0, 2, 0
if flt[0] < 4, 2, -1
getactorsdist 1, 2, 0
if flt[0] < 4, 2, 1

label 2
frm_seton 100, 1
act_setstate 3, active
act_setstate 4, off
act_setstate 5, off
act_setstate 6, off
act_setstate 100, off