dim_flt 1
dim_act 6
findactor 0, "speedster"
findactor 1, "arrow"
findactor 2, "Guard"
findactor 3, "Bguard"
findactor 4, "Muz"
findactor 5, "Muz2"

act_setstate 100, inactive

label 1
wait 1000
ifplayerstealcar 0, 0
if flt[0] = 1, 2, -1
wait 1000
ifplayerstealcar 1, 0
if flt[0] = 1, -1, 1

label 2
setevent 2, 1, 2

label 3
setevent 3, 1, 2

wait 2000

label 4
setevent 4, 2, 4

label 5
setevent 5, 2, 5

act_setstate 100, off