dim_flt 1
dim_act 7
findactor 0, "polimFor"
findactor 1, "polimTud"
findactor 2, "2hearseA"
findactor 3, "1pol"
findactor 4, "1pol2"
findactor 5, "2pol"
findactor 6, "2pol2"

label 1
ifplayerstealcar 0, 0
if flt[0] = 1, 2, -1

ifplayerstealcar 1, 0
if flt[0] = 1, 2, -1

ifplayerstealcar 2, 0
if flt[0] = 1, -1, 1

label 2
setevent 3, 4, 2

label 3
setevent 4, 3, 3

label 4
setevent 5, 1, 4

label 5
setevent 6, 1, 5

act_setstate 100, off