dim_flt 2
dim_act 2
findactor 0, "Tommy"
findactor 1, "Delnik"

label 1
getactorsdist 0, 1, 0
if flt[0] < 10, -1, 1
human_anyweaponinhand 0, 0
if flt[0] = 1, -1, 1

label 2
setevent 1, 4, 2
wait 10000

label 3
wait 5000
let flt[1] = 1
getactorsdist 0, 1, 0
if flt[0] > 10, -1, 4
let flt[1] = flt[1] + 1

label 4
human_anyweaponinhand 0, 0
if flt[0] = 1, 5, -1
let flt[1] = flt[1] + 1

label 5
if flt[1] > 0, -1, 3

label 6
setevent 1, 5, 6
goto 1