commandblock 1
dim_act 7
dim_flt 1

findactor 0,"Enemy"
findactor 1,"Enemy04K"
findactor 2,"Enemy08K"
findactor 3,"Enemy09K"
findactor 4,"Enemy10K"
findactor 5,"Enemy11K"
findactor 6,"Enemy12K"

enemy_group_new 0
enemy_group_add 0,0
enemy_group_add 0,1
enemy_group_add 0,2
enemy_group_add 0,3
enemy_group_add 0,4
enemy_group_add 0,5
enemy_group_add 0,6
commandblock 0

enemy_lockstate fight_guard,3


