commandblock 1
dim_flt 1
dim_act 3
dim_frm 1
findactor 0,"Tommy"
findactor 1,"GodzMan9"
findactor 2,"Box366"

findframe 0,"mlaceni Sama"

enemy_vidim 0
frm_seton 0,0

door_enableus 2,0

act_setstate -1,inactive
commandblock 0


{ down
wait 3000
frm_seton 0,1
label 101
wait 30000
goto 101
}

wait 5000
door_lock 2,0
door_open 2,1

enemy_talk 04990291

enemy_podvadim_jak tretera
enemy_vidim 1
enemy_naserse 0

label XX
wait 60000
goto XX
end


event 201
return