dim_flt 1
dim_act 1
findactor 0, "cad_phaeton"

act_setstate -1, inactive
label 1
iscarusable 0, 0
if flt[0] = 0, -1, 1
wait 2000
iscarusable 0, 0
if flt[0] = 0, -1, 1
wait 2000
iscarusable 0, 0
if flt[0] = 0, -1, 1
wait 2000
iscarusable 0, 0
if flt[0] = 0, -1, 1
wait 2000
iscarusable 0, 0
if flt[0] = 0, -1, 1
wait 2000
iscarusable 0, 0
if flt[0] = 0, -1, 1
wait 2000
iscarusable 0, 0
if flt[0] = 0, -1, 1
wait 2000
iscarusable 0, 0
if flt[0] = 0, -1, 1
endofmission 0, 13980002