// ******************** test casu *************************
dim_flt 1
dim_act 1
findactor 0, "Salieri"

act_setstate -1, inactive
wait 10000
label 1
setevent 0, 2, 1
wait 300000
label 2
setevent 0, 3, 2
wait 60000
label 3
setevent 0, 4, 3
wait 60000
label 4
setevent 0, 5, 4
wait 60000
if flt[0] = 1, 5, -1
let flt[0] = 1
goto 2

label 5
wait 60000
setevent 0, 8, 5
wait 5000
endofmission 0, 13980000
