// ********************** test vzdalenost *********************
dim_flt 1
dim_act 2
findactor 0, "Tommy"
findactor 1, "Salieri"

act_setstate -1, active
wait 25000
label 1
wait 1000
getactorsdist 0, 1, 0
if flt[0] > 5, -1, 1
label 2
setevent 1, 6, 2
wait 4000
getactorsdist 0, 1, 0
if flt[0] > 5, -1, 6
label 3
setevent 1, 7, 3
wait 4000
getactorsdist 0, 1, 0
if flt[0] > 5, -1, 6
label 4
setevent 1, 8, 4
wait 5000
label 5
setevent 1, 9, 5
end
label 6
setevent 1, 10, 6
goto 1