//vitr nad krajem

dim_flt 2
dim_frm 1
FindFrame 0,"ambikrajina"

frm_seton 0,0

act_setstate -1,inactive

soundfade 0, 10000, 0, 1

label 10
  rnd 0, 5                   
  let flt[0] = flt[0] * 500
  let flt[0] = flt[0] + 2500
  wait flt[0]
  soundfade 0, 4000, 1, 0.4
  rnd 1, 5                  
  let flt[1] = flt[1] * 700 
  let flt[1] = flt[1] + 1000  
  wait flt[1]
 soundfade 0, 2200, 0.4, 1
goto 10