dim_flt 2
dim_act 4
dim_frm 2
findactor 2,"Paulie"
findactor 1,"Sam"
findactor 0,"Tommy"
findactor 3,"NULL"

findframe 0,"Paulie"
findframe 1,"Sam"

act_setstate -1, inactive

label 101
wait 1000
detector_inrange 0, 30
if flt[0] = 3,-1, 101

compareownerwithex 0,3,BEZAUTA,-1


change_mission "mise04-motorest", "load z mise04-mesto", 0
end

label BEZAUTA
if flt[1]=0,-1,101
human_talk 2,00950013,0
let flt[1]=1
goto 101