commandblock 1

zatmyse 1,1
dim_frm 3
findframe 0,"Tommy"
findframe 1,"frank"
findframe 2,"Salieri"

frm_seton 0,0
frm_seton 1,0
frm_seton 2,0
commandblock 0

subtitle_add 7203
wait 5000

commandblock 1
loaddifferences "dif09a.chg"
recloadfull "record09a.rep"
commandblock 0

recwaitforend

commandblock 1
recunload
cleardifferences

frm_seton 0,1
frm_seton 1,1
frm_seton 2,1
zatmyse 0
commandblock 0

wait 500
mission_objectivesclear
mission_objectives 09960001