dim_flt 1
dim_act 6
findactor 0, "Homeless5"
findactor 1, "Hoolig9"
findactor 2, "Hoolig12"
findactor 3, "spusteni hadky"
findactor 4, "chuligan hlaska"
findactor 5, "Hoolig8"

act_setstate 100, inactive

label 1
detector_inrange 0, 3
if flt[0] = 1, -1, 1

act_setstate 0, active
act_setstate 1, active
act_setstate 2, active
act_setstate 3, active
act_setstate 4, active
act_setstate 5, active

act_setstate 100, off