dim_flt 1
dim_act 1
dim_frm 2
findactor 0, "Tommy"
findframe 0, "2crowbar"
findframe 1, "Tomdrop"

label 1
detector_waitforuse 17970000
human_canaddweapon 0, 25, 0
if flt[0] = 1, -1, 2

player_lockcontrols 1
frm_seton 1, 1
person_playanim 0, "sbiranizeme01.i3d"
wait 600
commandblock 1
human_addweapon 0, 25, 0, 0
frm_seton 0, 0
commandblock 0
wait 600
person_stopanim 0
player_lockcontrols 0
end

label 2
console_addtext 3500
goto 1