dim_flt 1
dim_act 7
findactor 0,"HlidacBob"
findactor 1,"detector_autodrom"
findactor 2,"NULL"
findactor 4,"alfa2"
findactor 5,"pojistka01"
findactor 6,"pojistka02"


ACT_SETSTATE -1,inactive

label 101
wait 500
detector_inrange 0,50
if flt[0]=1,-1,101
compareownerwithex 0,2,102,-1
human_getowner 0,3
car_getspeed 3,0
if flt[0]=0,102,101


label 102
enemy_forcescript 0
detector_setsignal -1,1

//aktivace auta
act_setstate 4,active

act_setstate 5,off
act_setstate 6,off
