dim_flt 1
dim_frm 1
dim_act  3
findframe 0,"detector_hlidac"

findactor 0,"HlidacBob"
findactor 1,"detector_hlidac"
findactor 2,"NULL"

setcompass 0
timeron 12,43,0,720
settimeoutevent 1,202

label 102
detector_inrange 0,10
if flt[0]=1,-1,102
setcompass -1
label 101
setevent 0,201,101

label 222
wait 500
compareownerwithex 0,2,222,-1
setevent 0,202,222
label 333
wait 60000
goto 333
end

event 202
timeroff
endofmission 0,05980001,"05990221.wav"
return