dim_frm 1
dim_flt 4
dim_act 3
findactor 0, "Tommy"
findactor 1, "Guard"
findactor 2, "Guard2"
findframe 0, "Guard2"
setcompass 0

label 1
human_getproperty 0, 0, energy
human_getproperty 1, 1, energy
human_getproperty 2, 2, energy
if flt[1] < 50, 2, -1
if flt[2] < 50, 2, -1
if flt[0] = 0, -1, 1
wait 5000
endofmission 0, 13980002

label 2
wait 4000
endofmission 0, 14980002

event 1
wait 4000
endofmission 0, 13980002

