dim_flt 1
dim_act 3
findactor 0,"Tommy"
findactor 1,"Czena2"
findactor 2,"waiter"

dim_flt 1
human_looktoactor 1

enemy_lockstate panic_runaway,30

{ up
enemy_playanim "Mise zidle01st.I3D", 0
label 1
wait 15000
goto 1
}

event 1
HUMAN_LOOKTOACTOR 1, 2, 1
debug_text "2x Desert Eagle prosim Vas."
wait 4500
HUMAN_LOOKTOACTOR 1
return

event use_ab,02970002 
getenemyaistate 1,0
iffltinrange 0,2,5,120
HUMAN_LOOKTOACTOR 1, 0, 1
enemy_talk 08950011
enemy_wait
HUMAN_LOOKTOACTOR 1
label 120
return
