dim_flt 1
dim_act 2
dim_frm 2
findactor 0
findactor 1, "detector_life1"
findframe 0, "Sniperka"
findframe 1, "2bar"
createweaponfromframe 1, 3, 0, 0
frm_seton 0, 1

label FREESTATE
enemy_playanim "Mise zidle01d.I3D"
rnd 0, 5
let flt[0] = flt[0] + 1
let flt[0] = flt[0] * 2000
wait flt[0] 
enemy_playanim "Mise zidle01c.I3D", 0
let flt[0] = flt[0] - 83
wait flt[0]
goto FREESTATE

event ENEMY_TO_AI
frm_seton 0, 0
act_setstate 1, off
human_addweapon 0, 14, 5, 30
return