dim_act 2
findactor 0
findactor 1, "Tommy"
human_addweapon 0, 10, 50, 200
{ DOWN
label GUARD
enemy_move 19
enemy_action_backlook 5000
enemy_action_sidelook 1, 3000
enemy_move 20
enemy_action_backlook 5000
enemy_action_sidelook 1, 2000
enemy_move 21
enemy_action_backlook 5000
enemy_action_sidelook 1, 7000
goto GUARD
}
enemy_naserse 1
enemy_action_fire 1
debug_text "Guard5: ALARM"
goto FINISH

event 1
event_use_cb 1
enemy_forcescript 0
return

label FINISH