commandblock 1
dim_act 3
dim_flt 2
findactor 0, "Tommy"
findactor 1, "Kasar"
findactor 2, "2x load mise11-mesto2"
commandblock 0
act_setstate -1, inactive

label 1
detector_inrange 0, 7
if flt[0] = 1, -1, 1
commandblock 1
getactorsdist 0, 1, 0
human_isweapon 0, 1, 19
if flt[0] > 15, 2, -1
if flt[1] = 0, 3, -1
character_push 1
commandblock 0
label 4
setevent 2, 2, 4
end

label 2
commandblock 0
human_talk 0, 11990331
wait 7000
goto 1

label 3
commandblock 0
human_talk 0, 11990371
wait 7000
goto 1