dim_act 8
dim_flt 1

commandblock 1
findactor 0, "Enemy08K"
findactor 1, "Enemy10K"
findactor 2, "Enemy04K"
findactor 3, "Enemy11K2"
findactor 4, "Enemy09K"
findactor 5, "Enemy10K2"
findactor 6, "Enemy08K3"
findactor 7, "Radni"
commandblock 0


label 1
getenemyaistate 7, 0
if flt[0] > 1, -1, 1

setevent 7, 1, -1
setevent 0, 5, -1
setevent 1, 5, -1
setevent 2, 5, -1
setevent 3, 5, -1
setevent 4, 5, -1
setevent 5, 5, -1
setevent 6, 5, -1
