dim_flt 1
dim_act 5
findactor 0, "2bomb"
findactor 1, "Tommy"
findactor 2, "null"
//findactor 3, "zjisteni auta"
findactor 4, ""

label 1
detector_inrange 0, 3
if flt[0] = 1, -1, 1

detector_issignal 0, 2, -1
human_talk 1, 00950100, 4
wait 10000
goto 1

label 2
compareownerwithex 1, 2, -1, 3
findnearactor 4, 3, car
getactorsdist 3, 4, 0
if flt[0] < 4, 1, -1

label 3
change_mission "mise15-mesto", "load z mise15-saliery", 4
