act_setstate -1, inactive
dim_flt 2
dim_act 1
findactor 0, "Bookmaker"

label PREDETECT
detector_inrange 0, 50
if flt[0] ! 0, -1, PREDETECT
gosub SAY


label DETECT
detector_inrange 0, 10
wait 200
if flt[0] ! 0, -1, NOONE
if flt[1] = 1, DETECT, -1
let flt[1] = 1
detector_setsignal -1, 1
goto DETECT

label NOONE
if flt[1] = 1, -1, DETECT
let flt[1] = 0
detector_setsignal -1, 0
goto DETECT


label SAY
human_talk 0, 02950065, 4
return