commandblock 1
   dim_act 2
   findactor 0, "Sam"
   getactiveplayer 1
//   dim_frm 1
//   findframe 0, "Sam"
   dim_flt 1
commandblock 0

act_setstate -1, inactive

label DETECT
wait 1000
getactorsdist 0, 1, 0
if flt[0] > 50, -1, DETECT

act_setstate 0, inactive
debug_text "detector_vypni_Sama: Sam vypnut!"

label DETECT2
wait 1000
getactorsdist 0, 1, 0
if flt[0] < 40, -1, DETECT2

act_setstate 0, active
debug_text "detector_vypni_Sama: Sam zapnut!"
goto DETECT