dim_flt 1

act_setstate 100, inactive

enemy_lockstate panic_freeze

frm_seton 100, 1

label 1
enemy_playanim "gesto_03c.i3d", 0, simple
let flt[0] = flt[0] - 323
wait flt[0]
enemy_playanim "gesto_03a.i3d"
wait 3000
enemy_playanim "gesto_03d.i3d", 0, simple
let flt[0] = flt[0] - 323
wait flt[0]
enemy_playanim "gesto_03a.i3d"
wait 2000
enemy_playanim "gesto_03e.i3d", 0, simple
let flt[0] = flt[0] - 323
wait flt[0]
enemy_playanim "gesto_03a.i3d"
wait 3000
goto 1