dim_flt 1

act_setstate 100, inactive

enemy_lockstate panic_freeze

frm_seton 100, 1

label 1
enemy_playanim "gesto_01c.i3d", 0, simple
let flt[0] = flt[0] - 323
wait flt[0]
enemy_playanim "gesto_01a.i3d"
wait 1500
enemy_playanim "gesto_01d.i3d", 0, simple
let flt[0] = flt[0] - 323
wait flt[0]
enemy_playanim "gesto_01a.i3d"
wait 1000
enemy_playanim "gesto_01e.i3d", 0, simple
let flt[0] = flt[0] - 323
wait flt[0]
enemy_playanim "gesto_01a.i3d"
wait 1000
goto 1