dim_flt 1
dim_act 6
findactor 0, "Paulie"
findactor 1, "zastavka 3"
findactor 2, "civil8"
findactor 3, "civil7"
findactor 4, "civil9"
findactor 5, "Czena3"

act_setstate 100, inactive

label 1
detector_inrange 0, 10
if flt[0] = 1, -1, 1

act_setstate 4, active
act_setstate 5, active

label 2
setevent 0, 2, 2
act_setstate 1, active

act_setstate 2, active
act_setstate 3, active

act_setstate 100, off