// zapne mne prijeti k servisu
act_setstate -1, inactive
///////////////////////////////ef1

DIM_FRM 3
DIM_FLT 2

FINDFRAME 0, "ef1"
FINDFRAME 1, "ef2"
FINDFRAME 2, "ef3"

label 1
  rnd 0, 10  
  let flt[0] = flt[0] * 2800 
  let flt[0] = flt[0] + 8000
  wait flt[0]
 rnd 1, 12
 IFFLTINRANGE 1, 0, 3, 2
 IFFLTINRANGE 1, 4, 7, 3
 IFFLTINRANGE 1, 8, 11, 4

label 2
 FRM_SETON 0, 1
goto 1

label 3
 FRM_SETON 1, 1
goto 1

label 4
 FRM_SETON 2, 1
goto 1