dim_flt 2
dim_frm 1
dim_act 1
findactor 0
findframe 0, "s_whimran"
setnoanimhit 0, 1
enemy_vidim 0

{ DOWN
label FREESTATE
commandblock 0
enemy_playanim "Mise03E_Salieri02.I3D", 0
let flt[0] = flt[0] - 250
wait flt[0]
commandblock 1
rnd 0, 3
let flt[0] = flt[0] + 1
if flt[0] = 1, -1, FREESTATE
frm_seton 0, 1
goto FREESTATE
}
goto FINISH

event HIT_FROM_PLAYER
if flt[1] ! 0, RET, -1
enemy_playanim "x sed panika01.I3D", 0
event_use_cb 1
let flt[1] = flt[1] + 1
label RET
return

label FINISH
