dim_flt 1
dim_act 6
findactor 0, "Tommy"
findactor 1, "Sam"
findactor 2, "Mesh43"
findactor 3, "Mesh83"
findactor 4, "vypnuti hudby"
// smazat
findactor 5, "Mesh01"

act_setstate 100, inactive

label 1
detector_inrange 0, 3
if flt[0] = 1, -1, 1

human_talk 0, 20990151

door_lock 2, 0
door_lock 3, 0
door_open 3, 1
act_setstate 1, active
act_setstate 4, active
// smazat
door_lock 5, 0
act_setstate 100, off