dim_act 3
dim_frm 4
findactor 0, ""
findactor 1, "pontTud"
findactor 2, "Czena5"
findframe 0, ""
findframe 1, "pontTud"
findframe 2, "Czena5"
findframe 3, "navadeni auta 2"

act_setstate 100, inactive

enemy_move 33
enemy_lookto 32
enemy_wait

label 1
enemy_usecar 1, 0
compareownerwith 1, -1, 1

wait 2000

enemy_car_moveto 1, 3

frm_seton 0, 0
frm_seton 1, 0
frm_seton 2, 0
act_setstate 1, off
act_setstate 2, off
act_setstate 0, off