dim_flt 1
dim_act 2
dim_frm 1
findactor 0, "pontTud2"
findactor 1, "detekce auto ve vode"
findframe 0, "load mise17-saliery"

act_setstate 100, inactive

car_switchshowenergy 0, 1

label 1
getcardamage 0, 0
if flt[0] = 0, -1, 1

act_setstate 1, off

setcompass -1
mission_objectivesclear
mission_objectives 20960004
wait 4000
mission_objectivesclear
mission_objectives 17960001
setcompass 0
act_setstate 100, off