dim_flt 3
dim_act 2
dim_frm 1
findactor 0, "1Bclerk"
findactor 1, "1Bclerk2"
findframe 0, "zvonek_poplach"

act_setstate 100, inactive

label 1
detector_inrange 0, 2
if flt[0] = 1, -1, 1

human_getproperty 0, 0, energy
if flt[0] = 0, -1, 2
let flt[1] = flt[1] + 1

label 2
human_getproperty 1, 0, energy
if flt[0] = 0, -1, 3
let flt[1] = flt[1] + 1

label 3
if flt[1] = 2, 4, -1

frm_seton 0, 1
detector_setsignal 100, 1

label 4