dim_flt 2
dim_act 1
findactor 0, "Tommy"

let flt[1] = 2

act_setstate 100, inactive

label 1
detector_waitforuse
policeitchforplayer 0
if flt[0] = 1, -1, 5
goto flt[1]

label 2
human_talk 0, 00950224, 4
let flt[1] = flt[1] + 1
goto 1

label 3
human_talk 0, 00950223, 4
let flt[1] = flt[1] + 1
goto 1

label 4
human_talk 0, 00950225, 4
let flt[1] = 2
goto 1

label 5
detector_setsignal 100, 1

act_setstate 100, inactive
goto 1