dim_flt 1
dim_act 2
dim_frm 1
findactor 0, "Tommy"
findactor 1, "Czena"
findactor 2, "
findframe 0, "Czena"

act_setstate 100, inactive

label 1
getactorsdist 0, 1, 0
if flt[0] < 10, -1, 1

wait 4000

getactorsdist 0, 1, 0
if flt[0] < 10, -1, 1

label 2
setevent 1, 1, 2

act_setstate 100, inactive
wait 10000
goto 1

event 1
label 3
getactorsdist 0, 1, 0
if flt[0] > 200, -1, 3

frm_seton 0, 0
act_setstate 1, off
act_setstate 100, off