dim_flt 5
dim_act 4
findactor 0, "Tommy"
findactor 1, "Kasar"
findactor 2, "Ralph"
findactor 3, "Kasar2"

label 1
human_getproperty 0, 0, energy
human_getproperty 1, 1, energy
human_getproperty 2, 3, energy
human_getproperty 3, 4, energy
if flt[4] = 0, 4, -1
if flt[3] = 0, 3, -1
if flt[0] = 0, 2, -1
if flt[1] = 0, -1, 1
label 4
wait 4000
endofmission 0, 11980000

label 2
wait 1000
endofmission 0, 13980002

label 3
wait 4000
endofmission 0, 10980007
