dim_act 3
findactor 0,"detector_bombcar"
findactor 1,"activate_bombcar"
findactor 2,"AKTIVNI_SUBQUEST"

enemy_vidim 0

label START
{ down
label 101
enemy_playanim "Mavani01.I3D"
wait 30000
goto 101
}
detector_issignal 2,START,-1

detector_setsignal 2,1

act_setstate 0,active

human_eraseab 1
enemy_stopanim
label 102
wait 50000
goto 102
end

event use_ab,10970007
detector_issignal 2,NELZE,-1
autosavegamefull 5590
goto JMP01
label NELZE
console_addtext 3474
label JMP01
return
