act_setstate -1,inactive
dim_act 2
dim_flt 1
findactor 0,"fuckoff_badend"
findactor 1,"activate_fuckoff"

timeron 0,0,0,300
settimeoutevent 0,201

label 101
wait 2000
human_getproperty 1,0,Energy
if flt[0]=0,-1,101

mission_objectivesclear
endofmission 0,22980001
end

event 201
settimeoutevent -1,201
timeroff
mission_objectivesclear
endofmission 0,22980001
end

event 202
settimeoutevent -1,201
timeroff
end
