dim_flt 1
dim_act 4
findactor 0, "spusteni dialogu"
findactor 1, "VincenzoHIGH"
findactor 2, ""
findactor 3, "Tommy"

wingman_setindicator 2, 2, 2

{ down
enemy_move 2
enemy_lookto 3
enemy_wait

label 1
setevent 0, 1, 1
}

human_looktoactor 2, 1, 1

label 2
if flt[0] = 1, -1, 2

wait 2000
enemy_action_follow 3, 2

label 3
wait 1000000
goto 3

event 1
let flt[0] = 1
return

event 1000
label 1000
enemy_action_fire 3
goto 1000

event 2
event_use_cb 1
enemy_forcescript 2
enemy_stop
return