DIM_FRM 4
DIM_FLT 2

FINDFRAME 0, "smich1"
FINDFRAME 1, "smich2"
FINDFRAME 2, "brk"
FINDFRAME 3, "smich3"

label 1
  rnd 0, 5  
  let flt[0] = flt[0] * 2363
  let flt[0] = flt[0] + 10360
  wait flt[0]
 rnd 1, 12
 IFFLTINRANGE 1, 0, 3, 2
 IFFLTINRANGE 1, 4, 7, 3
 IFFLTINRANGE 1, 8, 11, 4

label 2
 FRM_SETON 0, 1
goto 1

label 3
 FRM_SETON 1, 1
goto 1

label 4
 FRM_SETON 2, 1
wait 950
 FRM_SETON 3, 1
goto 1