dim_flt 2
dim_act 3
dim_frm 1
findframe 0, "Tommy"
findactor 0, "Tommy"
findactor 1, "Salieri"
findactor 2, "load mise13-zradce"

label 2
detector_waitforuse
vlvp 0
if flt[0] = 1, 1, -1
wait 500
vlvp 0
if flt[0] = 1, 1, -1
character_push 1
actor_setplacement 2, 1
change_mission "mise13-zradce", "load z mise13-mesto2", 0

label 1
if flt[1] = 1, -1, 3
human_talk 0, 00950223
wait 3000
let flt[1] = 0
goto 2
label 3
human_talk 0, 00950225
wait 3000
let flt[1] = 1
goto 2