enemy_vidim 0
dim_act 2
dim_flt 1
findactor 0, "Tommy"
findactor 1, "Salieri"

character_pop 1
wingman_setindicator 1, 3, 0

mission_objectivesclear
mission_objectives 13960002

{ up
enemy_action_follow 0, 2
label 1
wait 30000
goto 1
}

event 1
event_use_cb 1
enemy_talk 13990021
enemy_wait
return

event 5
event_use_cb 1
enemy_naserse 0
return

event use_ab 10970004
event_use_cb 1
human_looktoactor 1, 0, 1
human_talk 1, 00950121
human_looktoactor 1
return