dim_flt 1
dim_act 1
findactor 0, "Tommy"

act_setstate 100, inactive

enemy_changeanim "walk1.i3d", "chuzerucezazady1.i3d"

frm_seton 100, 1

label 1
enemy_move 16
enemy_lookto 17
enemy_wait
enemy_playanim "polst01.i3d", 0, simple
let flt[0] = flt[0] - 323
wait flt[0]
enemy_playanim "polst03.i3d"
wait 10000
enemy_playanim "polst04.i3d", 0, simple
let flt[0] = flt[0] - 323
wait flt[0]
enemy_stopanim
enemy_move 18
enemy_lookto 19
enemy_wait
wait 3000
goto 1

event 1
enemy_action_fire 0