dim_flt 1
dim_act 7
findactor 0, "cad_ford2"
findactor 1, "hudfor"
findactor 2, "Enemy12K3"
findactor 3, "Enemy7"
findactor 4, "Enemy04K2"
findactor 5, "Enemy08K2"
findactor 6, "Enemy11K2"


label 1
wait 1000
ifplayerstealcar 0, 0
if flt[0] = 1, 2, -1
wait 1000
ifplayerstealcar 1, 0
if flt[0] = 1, -1, 1

label 2
setevent 2, 1, 2

label 3
setevent 3, 1, 3

label 4
setevent 4, 1, 4

label 5
setevent 5, 1, 1

label 6
setevent 6, 1, 1

act_setstate 100, off