dim_flt 1
dim_act 6
findactor 0, "Sergio"
findactor 1, "Enemy7"
findactor 2, "Enemy11K2"
findactor 3, "Enemy04K2"
findactor 4, "Enemy08K2"
findactor 5, "Enemy12K3"

act_setstate 100, inactive

label 1
wait 500
detector_inrange 0, 10
if flt[0] = 1, -1, 1

label 2
setevent 0, 2, 2

label 3
setevent 1, 1, 3

label 4
setevent 2, 1, 4

label 5
setevent 3, 1, 5

label 6
setevent 4, 1, 6

label 7
setevent 5, 1, 7

act_setstate 100, off